#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 10 12:14:00 2021

@author: xiao
"""

#fname = input("Enter file name: ")

    
fname = "mbox-short.txt"
    
count = 0

fh = open(fname)
for line in fh:
    line = line.rstrip()
    if line.startswith('From:') or not line.startswith('From'): continue
    words = line.split()
    print(words[1])
    count = count + 1
    
××
